### ISSUE TITLE
unable to remove border

### ISSUE THREAD

**Issue by Zignand** [Lawris/Plassonade-s-Dashbaord#4]
Hi Lawris, 
thank you for the climate card – it's awesome! 
Could you suggest a way to remove the light borders I have?
![image](https://github.com/user-attachments/assets/97c49a5b-163c-481b-833e-2bfd1e659304)

Thank you!

**Comment by Lawris** [comment]
Hello @Zignand ! Do you have card_mod installed?

**Comment by Zignand** [comment]
Yes! 
![Immagine WhatsApp 2024-09-16 ore 09 13 03_4707faf5](https://github.com/user-attachments/assets/163ba7d7-228a-498d-afb6-6be92bfa6f1d)

**Comment by bohoffi** [comment]
@Zignand I came across the same issue that `border: none;` wasn't working but I found a solution. Instead of
```css
ha-card {
  border: none;
}
```
I'm using
```css
ha-card {
  --ha-card-border-width: 0;
}
```

In case you want to remove the border of a chip as well it's
```css
ha-card {
  --chip-border-width: 0;
}
```
